Concurrent ERC2771
gelatodigital/relay-contracts pull request #71
Opened 2023-07-28 07:26 UTC by bennoprice

2023-07-28 07:32 UTC, gitpusha commented on contracts/GelatoRelay1BalanceConcurrentERC2771.sol
> +        _requireHash(
rename to `_requireReplayProtection`

2023-07-28 07:49 UTC, gitpusha commented on contracts/GelatoRelayConcurrentERC2771.sol
> +        _requireHash(
rename

2023-07-28 08:17 UTC, gitpusha commented on deploy/GelatoRelay1BalanceConcurrentERC2771.deploy.ts
> +    devRelayERC2771Deployer,
We have to remove those later and replace with new deployer keys

2023-08-05 14:42 UTC, jack-the-pug approved these changes
LGTM!

2023-08-07 08:03 UTC, denis-pingin requested changes

2023-08-07 08:03 UTC, denis-pingin commented on deploy/GelatoRelay1BalanceConcurrentERC2771.deploy.ts
> +    devRelayERC2771Deployer,
The code should be updated to use a new deployment key for both new contracts and add `dependencies` config

2023-08-07 08:03 UTC, denis-pingin commented on deploy/GelatoRelay1BalanceConcurrentERC2771.deploy.ts
> +//import { setCode } from "@nomicfoundation/hardhat-network-helpers";
Commented out code should be either removed or added back, depending on what makes sense

2023-08-22 17:22 UTC, denis-pingin approved these changes

2023-08-22 19:00 UTC, merged