Feat/GN-4325 Gas Optimisation
gelatodigital/relay-contracts pull request #77
Opened 2023-11-06 15:17 UTC by bennoprice

## Motivation

 

## Solution

## Security Considerations

### Roles and permissions

- [ ] It's Permissionless!
- [x] Roles and permissions listed below:

`sponsoredCall` remains unchanged and has the same roles and permissions as before - it can only be called by the diamond. `sponsoredCallV2` is permissionless and nothing is verified on-chain - it is the responsibility of the backend to properly verify the emitted signature off-chain given the payload.

### External Contracts

- [x] No external contracts.
- [ ] External contracts listed below:

### Deployment

Is this a new deployment or an upgrade to a deployed upgradable contract?

- [x] New deployment.
- [ ] Upgrade to a deployed upgradable contract:

### FUNDS AND PRIVILEGES

Does the contract hold any funds or privileges?

- [x] No funds, allowance, or privileges.
- [ ] Some:

## Checklist

- [x] I have performed a self-review of my code
- [x] If it is a new feature, I have added thorough tests.
- [ ] I have run your code through basic code analysis tools (Slither)
- [x] Solidity does not emit ANY compiler warnings.
- [x] The code is well-documented
- [x] The code has been deployed and tested on a forking network

2023-11-15 11:41 UTC, denis-pingin approved these changes

2023-11-15 12:02 UTC, denis-pingin requested changes

2023-11-15 12:02 UTC, denis-pingin commented on contracts/GelatoRelay1Balance.sol
> +    function sponsoredCallV2(
Please add the docs header comments section

2023-11-15 12:28 UTC, denis-pingin approved these changes

2023-11-27 14:25 UTC, denis-pingin approved these changes

2023-12-11 11:24 UTC, denis-pingin approved these changes

2024-02-08 12:18 UTC, denis-pingin approved these changes

2024-02-08 12:26 UTC, opatavi approved these changes

2024-02-08 12:26 UTC, merged